// <auto-generated />
using System;
using IntacoWebDemoForm.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IntacoWebDemoForm.Migrations
{
    [DbContext(typeof(IntacoWebDemoFormContext))]
    partial class IntacoWebDemoFormContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IntacoWebDemoForm.Models.Person", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddName");

                    b.Property<string>("E_Mail")
                        .IsRequired();

                    b.Property<string>("Kod_Pocztowy")
                        .IsRequired();

                    b.Property<string>("Miejscowosc")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Nazwa_Instytucji")
                        .IsRequired();

                    b.Property<string>("Telefon")
                        .IsRequired();

                    b.Property<string>("Token");

                    b.Property<string>("Ulica")
                        .IsRequired();

                    b.Property<string>("Username")
                        .IsRequired();

                    b.Property<bool>("Zgoda_Rodo");

                    b.Property<bool>("email_Verified");

                    b.Property<bool>("verified");

                    b.Property<DateTime>("verified_date");

                    b.HasKey("ID");

                    b.ToTable("Person");
                });
#pragma warning restore 612, 618
        }
    }
}
